require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

boost_podspec_path = File.expand_path(
  '../node_modules/react-native/third-party-podspecs/boost.podspec',
  __dir__
)
boost_source_old = 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2'
boost_source_new = 'https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2'
if File.exist?(boost_podspec_path)
  boost_podspec_contents = File.read(boost_podspec_path)
  if boost_podspec_contents.include?(boost_source_old)
    boost_podspec_contents = boost_podspec_contents.gsub(boost_source_old, boost_source_new)
    File.write(boost_podspec_path, boost_podspec_contents)
    Pod::UI.puts 'Patched boost podspec to use archives.boost.io'
  end
end

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Flipper is disabled - incompatible with newer Xcode versions
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LibsodiumExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'LibsodiumExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Xcode 26 / libc++ removes std::unary_function in C++17; boost 1.76 still references it.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        macro = '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION'
        define_flag = "-D#{macro}"

        cpp_flags = config.build_settings['OTHER_CPLUSPLUSFLAGS']
        cpp_flags = [cpp_flags] if cpp_flags.is_a?(String)
        cpp_flags = ['$(inherited)'] if cpp_flags.nil?
        cpp_flags << define_flag unless cpp_flags.include?(define_flag)
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cpp_flags

        c_flags = config.build_settings['OTHER_CFLAGS']
        c_flags = [c_flags] if c_flags.is_a?(String)
        c_flags = ['$(inherited)'] if c_flags.nil?
        c_flags << define_flag unless c_flags.include?(define_flag)
        config.build_settings['OTHER_CFLAGS'] = c_flags

        defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        defs = [defs] if defs.is_a?(String)
        defs = ['$(inherited)'] if defs.nil?
        defs << macro unless defs.include?(macro)
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
      end
    end
  end
end
